name: Profile Views Counter
on:
  schedule:
    - cron: '0 */12 * * *'  # Every 12 hours
  workflow_dispatch:

jobs:
  views:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate GitHub Profile Views Counter
        uses: arturssmirnovs/github-profile-views-counter@v2
        with:
          username: kilandrabass  # Replace with your username
          token: ${{ secrets.GITHUB_TOKEN }}
