name: Profile Views Counter  
on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:

jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - uses: lowiebenoot/profile-views-counter@main
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
