name: Profile Views Counter  
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
jobs:
  release:
    name: GitHub Profile Views Counter Action
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.INSIGHTS_TOKEN }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.17.0
      - uses: lowiebenoot/profile-views-counter@main
        env:
          INSIGHTS_TOKEN: ${{ secrets.INSIGHTS_TOKEN }}
